<script setup lang="ts">
import { PhPlus } from '@phosphor-icons/vue'
import { normalizeApiError } from '~/utils/api/errors'
import { PERMISSION_LABELS, hasPermission, PERMISSIONS } from '~/utils/permissions'
type Role = { name: string; label?: string; description?: string; permissions?: string[] }; type Permission = { key?: string; code?: string; label?: string; category?: string }
const { $api } = useNuxtApp(); const auth = useTenantAuth(); const canEdit = computed(() => hasPermission(auth.user.value, PERMISSIONS.UserEdit)); const roles = ref<Role[]>([]); const permissions = ref<Permission[]>([]); const draft = reactive<Record<string, string[]>>({}); const baseline = ref<Record<string, string[]>>({}); const loading = ref(false); const saving = ref(false); const error = ref(''); const showCreate = ref(false); const newRole = reactive({ name: '', description: '' })
const load = async () => { loading.value = true; error.value = ''; try { const [permissionList, roleList] = await Promise.all([$api.get<Permission[]>('/admin/permissions'), $api.get<Role[]>('/admin/roles')]); permissions.value = Array.isArray(permissionList) ? permissionList : []; roles.value = Array.isArray(roleList) ? roleList : []; Object.keys(draft).forEach(key => delete draft[key]); roles.value.forEach(item => { draft[item.name] = [...(item.permissions || [])] }); baseline.value = Object.fromEntries(roles.value.map(item => [item.name, [...(item.permissions || [])]])) } catch (cause) { error.value = normalizeApiError(cause, 'Roles could not be loaded.') } finally { loading.value = false } }
const dirty = computed(() => JSON.stringify(draft) !== JSON.stringify(baseline.value)); const toggle = (role: Role, code: string) => { if (!canEdit.value || role.name === 'SuperAdmin') return; const next = new Set(draft[role.name] || []); next.has(code) ? next.delete(code) : next.add(code); draft[role.name] = [...next] }
const save = async () => { saving.value = true; try { await Promise.all(roles.value.filter(role => JSON.stringify(draft[role.name] || []) !== JSON.stringify(baseline.value[role.name] || [])).map(role => $api.put(`/admin/roles/${encodeURIComponent(role.name)}`, { permissions: draft[role.name] || [] }))); await load() } catch (cause) { error.value = normalizeApiError(cause, 'Role permissions could not be saved.') } finally { saving.value = false } }
const createRole = async () => { if (!newRole.name.trim()) return; saving.value = true; try { await $api.post('/admin/roles', { name: newRole.name.trim(), description: newRole.description.trim(), permissions: [] }); showCreate.value = false; Object.assign(newRole, { name: '', description: '' }); await load() } catch (cause) { error.value = normalizeApiError(cause, 'Role could not be created.') } finally { saving.value = false } }
onMounted(load)
</script>
<template><section class="settings-card settings-access-panel"><header><div><h3>Roles &amp; permissions</h3><p>Control which areas each role can access. Protected administrator roles remain locked.</p></div><div class="settings-header-actions"><button v-if="dirty && canEdit" type="button" class="settings-secondary-button" @click="Object.assign(draft, baseline)">Discard</button><button v-if="dirty && canEdit" type="button" class="settings-primary-button" :disabled="saving" @click="save">{{ saving ? 'Saving…' : 'Save changes' }}</button><button v-if="canEdit" type="button" class="settings-secondary-button" @click="showCreate = true"><PhPlus :size="15" /> New role</button></div></header><p v-if="error" class="settings-alert">{{ error }}</p><div v-if="loading" class="settings-state">Loading roles…</div><div v-else class="settings-table-wrap"><table class="settings-permission-table"><thead><tr><th>Feature</th><th v-for="role in roles" :key="role.name">{{ role.label || role.name }}</th></tr></thead><tbody><tr v-for="permission in permissions" :key="permission.key || permission.code"><td><strong>{{ permission.label || PERMISSION_LABELS[(permission.key || permission.code || '') as keyof typeof PERMISSION_LABELS] || permission.key || permission.code }}</strong><small>{{ permission.category || 'Access' }}</small></td><td v-for="role in roles" :key="role.name"><input type="checkbox" :checked="draft[role.name]?.includes(permission.key || permission.code || '')" :disabled="!canEdit || role.name === 'SuperAdmin'" @change="toggle(role, permission.key || permission.code || '')" /></td></tr></tbody></table></div></section><div v-if="showCreate" class="settings-modal-backdrop" @click.self="showCreate = false"><form class="settings-modal" @submit.prevent="createRole"><h3>New role</h3><label>Name<input v-model="newRole.name" placeholder="Billing_Manager" required /></label><label>Description<input v-model="newRole.description" /></label><div class="settings-modal-actions"><button type="button" class="settings-secondary-button" @click="showCreate = false">Cancel</button><button type="submit" class="settings-primary-button" :disabled="saving">Create</button></div></form></div></template>
