<script setup lang="ts">
import { PhKey, PhMagnifyingGlass, PhPencilSimple, PhPlus } from '@phosphor-icons/vue'
import { normalizeApiError } from '~/utils/api/errors'
import { API_USER_ROLES, ALL_ROLES, formatRole, hasPermission, PERMISSIONS } from '~/utils/permissions'

type UserRow = { id: string; name?: string; email?: string; phone?: string; role?: string; specialty?: string; is_active?: boolean }
const { $api } = useNuxtApp(); const auth = useTenantAuth()
const canCreate = computed(() => hasPermission(auth.user.value, PERMISSIONS.UserCreate)); const canEdit = computed(() => hasPermission(auth.user.value, PERMISSIONS.UserEdit))
const rows = ref<UserRow[]>([]); const loading = ref(false); const saving = ref(false); const error = ref(''); const query = ref(''); const role = ref('all'); const status = ref('all'); const modal = ref<'create'|'edit'|'reset'|null>(null); const selected = ref<UserRow | null>(null); const temporaryPassword = ref('')
const form = reactive({ name: '', email: '', password: '', role: 'reception', specialty: '', phone: '' }); const resetForm = reactive({ new_password: '', generate_temporary: true })
const load = async () => { loading.value = true; error.value = ''; try { rows.value = await $api.get<UserRow[]>('/users', { limit: 500, ...(query.value ? { q: query.value } : {}), ...(role.value !== 'all' ? { role: role.value } : {}), ...(status.value !== 'all' ? { is_active: status.value === 'active' } : {}) }) } catch (cause) { error.value = normalizeApiError(cause, 'Users could not be loaded.') } finally { loading.value = false } }
const resetFormState = () => Object.assign(form, { name: '', email: '', password: '', role: 'reception', specialty: '', phone: '' })
const openCreate = () => { selected.value = null; resetFormState(); modal.value = 'create' }
const openEdit = (user: UserRow) => { selected.value = user; Object.assign(form, { name: user.name || '', email: user.email || '', password: '', role: user.role || 'reception', specialty: user.specialty || '', phone: user.phone || '' }); modal.value = 'edit' }
const saveUser = async () => { saving.value = true; error.value = ''; try { if (modal.value === 'create') await $api.post('/users', form); else if (selected.value) await $api.patch(`/users/${selected.value.id}`, { name: form.name, role: form.role, specialty: form.specialty, phone: form.phone }); modal.value = null; await load() } catch (cause) { error.value = normalizeApiError(cause, 'User could not be saved.') } finally { saving.value = false } }
const toggleActive = async (user: UserRow) => { try { await $api.post(`/users/${user.id}/${user.is_active === false ? 'enable' : 'disable'}`); await load() } catch (cause) { error.value = normalizeApiError(cause, 'User status could not be updated.') } }
const openReset = (user: UserRow) => { selected.value = user; Object.assign(resetForm, { new_password: '', generate_temporary: true }); temporaryPassword.value = ''; modal.value = 'reset' }
const resetPassword = async () => { if (!selected.value) return; saving.value = true; try { const result = await $api.post<{ temporary_password?: string }>(`/users/${selected.value.id}/reset-password`, resetForm); temporaryPassword.value = result.temporary_password || 'Password reset successfully.' } catch (cause) { error.value = normalizeApiError(cause, 'Password could not be reset.') } finally { saving.value = false } }
watch([query, role, status], load); onMounted(load)
</script>
<template>
  <section class="settings-card settings-access-panel"><header><div><h3><PhMagnifyingGlass :size="18" /> Users</h3><p>Manage people who can access this tenant workspace.</p></div><button v-if="canCreate" type="button" class="settings-primary-button" @click="openCreate"><PhPlus :size="16" /> Add user</button></header>
    <div class="settings-filter-row"><label class="settings-search"><PhMagnifyingGlass :size="16" /><input v-model="query" placeholder="Search name, email, or phone" /></label><select v-model="role"><option value="all">All roles</option><option v-for="item in ALL_ROLES" :key="item" :value="item">{{ formatRole(item) }}</option></select><select v-model="status"><option value="all">All status</option><option value="active">Active</option><option value="inactive">Disabled</option></select></div>
    <p v-if="error" class="settings-alert">{{ error }}</p><div v-if="loading" class="settings-state">Loading users…</div><div v-else-if="!rows.length" class="settings-empty">No users found.</div><div v-else class="settings-user-list"><article v-for="user in rows" :key="user.id"><div><strong>{{ user.name || 'Unnamed user' }}</strong><small>{{ user.email || user.phone || 'No contact recorded' }}</small></div><span>{{ formatRole(user.role) }}</span><span class="settings-status" :class="{ active: user.is_active !== false }">{{ user.is_active === false ? 'Disabled' : 'Active' }}</span><div class="settings-row-actions"><button v-if="canEdit" type="button" aria-label="Edit user" @click="openEdit(user)"><PhPencilSimple :size="16" /></button><button v-if="canEdit" type="button" aria-label="Reset password" @click="openReset(user)"><PhKey :size="16" /></button><button v-if="canEdit" type="button" @click="toggleActive(user)">{{ user.is_active === false ? 'Enable' : 'Disable' }}</button></div></article></div>
  </section>
  <div v-if="modal" class="settings-modal-backdrop" @click.self="modal = null"><form v-if="modal === 'create' || modal === 'edit'" class="settings-modal" @submit.prevent="saveUser"><h3>{{ modal === 'create' ? 'Add team member' : 'Edit user' }}</h3><label>Name<input v-model="form.name" required /></label><label v-if="modal === 'create'">Email<input v-model="form.email" type="email" required /></label><label v-if="modal === 'create'">Password<input v-model="form.password" type="password" required /></label><label>Role<select v-model="form.role"><option v-for="item in API_USER_ROLES" :key="item" :value="item">{{ formatRole(item) }}</option></select></label><label>Phone<input v-model="form.phone" /></label><label>Specialty<input v-model="form.specialty" /></label><div class="settings-modal-actions"><button type="button" class="settings-secondary-button" @click="modal = null">Cancel</button><button type="submit" class="settings-primary-button" :disabled="saving">{{ saving ? 'Saving…' : 'Save' }}</button></div></form><form v-else class="settings-modal" @submit.prevent="resetPassword"><h3>Reset password</h3><p>Reset password for <strong>{{ selected?.name }}</strong>.</p><label class="toggle-field"><input v-model="resetForm.generate_temporary" type="checkbox" /> Generate temporary password</label><label v-if="!resetForm.generate_temporary">New password<input v-model="resetForm.new_password" type="password" required /></label><p v-if="temporaryPassword" class="settings-success">{{ temporaryPassword }}</p><div class="settings-modal-actions"><button type="button" class="settings-secondary-button" @click="modal = null">Close</button><button type="submit" class="settings-primary-button" :disabled="saving">Reset password</button></div></form></div>
</template>
