<script setup lang="ts">
import { PhEnvelopeSimple, PhLockKey, PhUser } from '@phosphor-icons/vue'
import { normalizeApiError } from '~/utils/api/errors'
definePageMeta({ layout: false }); useHead({ title: 'Platform access' })
const auth = usePlatformAuth(); const checking = ref(true); const needsSetup = ref(false); const loading = ref(false); const error = ref(''); const form = reactive({ name: '', email: '', password: '', confirmPassword: '' })
onMounted(async () => { try { const result = await auth.setupStatus(); needsSetup.value = Boolean(result?.needs_setup) } catch { needsSetup.value = false } finally { checking.value = false } })
const submit = async () => { error.value = ''; if (needsSetup.value && form.password !== form.confirmPassword) { error.value = 'Passwords do not match.'; return }; if (needsSetup.value && form.password.length < 8) { error.value = 'Password must be at least 8 characters.'; return }; loading.value = true; try { if (needsSetup.value) await auth.bootstrap({ name: form.name, email: form.email, password: form.password }); else await auth.login(form.email, form.password); await navigateTo('/platform/tenants') } catch (cause) { error.value = normalizeApiError(cause, needsSetup.value ? 'Platform owner could not be created.' : 'Platform login failed.') } finally { loading.value = false } }
</script>
<template><main class="platform-login-page"><section class="platform-login-card"><div class="platform-login-brand"><span class="platform-brand-mark">C</span><div><strong>CureFlow</strong><small>Platform Console</small></div></div><div v-if="checking" class="platform-login-state">Checking platform setup…</div><template v-else><h1>{{ needsSetup ? 'Create platform owner' : 'Platform sign in' }}</h1><p class="platform-login-subtitle">{{ needsSetup ? 'Set up the first administrator for this installation.' : 'Manage hospitals and tenant lifecycle.' }}</p><form @submit.prevent="submit"><label v-if="needsSetup">Full name<div class="platform-input"><PhUser :size="17" /><input v-model="form.name" required minlength="2" placeholder="Your name" /></div></label><label>Email<div class="platform-input"><PhEnvelopeSimple :size="17" /><input v-model="form.email" type="email" required placeholder="ops@cureflow.in" /></div></label><label>Password<div class="platform-input"><PhLockKey :size="17" /><input v-model="form.password" type="password" required :minlength="needsSetup ? 8 : undefined" /></div></label><label v-if="needsSetup">Confirm password<div class="platform-input"><PhLockKey :size="17" /><input v-model="form.confirmPassword" type="password" required minlength="8" /></div></label><p v-if="error" class="platform-error">{{ error }}</p><button type="submit" class="platform-primary-button" :disabled="loading">{{ loading ? 'Please wait…' : needsSetup ? 'Create platform owner' : 'Sign in' }}</button></form></template></section></main></template>
