import { normalizeApiError } from '~/utils/api/errors'
import { normalizeSchedules, normalizeStaff, normalizeUsers, staffDepartments, type StaffMember, type StaffSchedule, type StaffUser } from '~/utils/staff'
import { hasPermission, PERMISSIONS } from '~/utils/permissions'
export type StaffDraft = { user_id: string; department: string; specialization: string; qualification: string; consultation_fee: string; employment_type: string; shift: string; ward_assignment: string; is_available: boolean }
const emptyDraft = (): StaffDraft => ({ user_id: '', department: '', specialization: '', qualification: '', consultation_fee: '', employment_type: 'permanent', shift: '', ward_assignment: '', is_available: true })
export const useStaff = () => {
  const { $api } = useNuxtApp(); const auth = useTenantAuth(); const staff = ref<StaffMember[]>([]); const users = ref<StaffUser[]>([]); const departments = ref<string[]>([]); const schedules = ref<StaffSchedule[]>([]); const selected = ref<StaffMember | null>(null); const loading = ref(false); const saving = ref(false); const error = ref(''); const draft = ref<StaffDraft>(emptyDraft()); let request = 0
  const load = async (tab = 'all', query = '') => { const current = ++request; loading.value = true; error.value = ''; try { const endpoint = tab === 'doctors' ? '/staff/doctors' : tab === 'nurses' ? '/staff/nurses' : '/staff'; const canLoadUsers = hasPermission(auth.user.value, PERMISSIONS.StaffCreate) && hasPermission(auth.user.value, PERMISSIONS.UserView); const requests = [$api.get<unknown>(endpoint, query ? { q: query } : undefined), $api.get<unknown>('/hospital-profile/departments')]; if (canLoadUsers) requests.push($api.get<unknown>('/users')); const results = await Promise.all(requests); const staffResult = results[0]; const departmentResult = results[1]; const userResult = canLoadUsers ? results[2] : null; if (current === request) { staff.value = normalizeStaff(staffResult); users.value = userResult ? normalizeUsers(userResult) : []; departments.value = staffDepartments(departmentResult) } } catch (cause) { if (current === request) error.value = normalizeApiError(cause, 'Hospital staff could not be loaded.') } finally { if (current === request) loading.value = false } }
  const open = async (member: StaffMember) => { selected.value = { ...member }; schedules.value = member.role === 'doctor' ? normalizeSchedules(await $api.get(`/staff/${member.id}/schedules`).catch(() => [])) : [] }
  const create = async () => { if (!draft.value.user_id) throw new Error('Select a user account.'); saving.value = true; try { await $api.post('/staff', { ...draft.value, consultation_fee: draft.value.consultation_fee ? Number(draft.value.consultation_fee) : null, department: draft.value.department || null, specialization: draft.value.specialization || null, qualification: draft.value.qualification || null, shift: draft.value.shift || null, ward_assignment: draft.value.ward_assignment || null }); draft.value = emptyDraft() } finally { saving.value = false } }
  const update = async () => { if (!selected.value) return; saving.value = true; try { await $api.patch(`/staff/${selected.value.id}`, { department: selected.value.department || null, specialization: selected.value.specialization || null, qualification: selected.value.qualification || null, consultation_fee: selected.value.consultation_fee ?? null, employment_type: selected.value.employment_type || 'permanent', shift: selected.value.shift || null, ward_assignment: selected.value.ward_assignment || null, is_available: selected.value.is_available }) } finally { saving.value = false } }
  const addSchedule = async (payload: Record<string, unknown>) => { if (!selected.value) return; await $api.post('/staff/schedules', { ...payload, staff_profile_id: selected.value.id, day_of_week: Number(payload.day_of_week), is_available: true }); schedules.value = normalizeSchedules(await $api.get(`/staff/${selected.value.id}/schedules`)) }
  onScopeDispose(() => { request++ }); return { staff, users, departments, schedules, selected, loading, saving, error, draft, load, open, create, update, addSchedule }
}
