import { normalizeApiError } from '~/utils/api/errors'
import { normalizeDepartments, normalizeSettingsList, shouldSendSecret, type HospitalProfile, type MessageTemplate } from '~/utils/settings'
export const useSettings = () => {
  const { $api } = useNuxtApp(); const profile = ref<HospitalProfile>({}); const departments = ref<string[]>([]); const integrations = reactive<{ whatsapp: Record<string, unknown>; sms: Record<string, unknown>; email: Record<string, unknown> }>({ whatsapp: {}, sms: {}, email: {} }); const templates = ref<MessageTemplate[]>([]); const notifications = ref<Array<Record<string, unknown>>>([]); const loading = ref(false); const saving = ref(false); const error = ref('')
  const load = async () => { loading.value = true; error.value = ''; try { const [hospital, whatsapp, sms, email, templateList, preferences] = await Promise.all([$api.get<HospitalProfile>('/hospital-profile'), $api.get<Record<string, unknown>>('/settings/whatsapp'), $api.get<Record<string, unknown>>('/settings/sms'), $api.get<Record<string, unknown>>('/settings/email'), $api.get<unknown>('/templates'), $api.get<unknown>('/notification-preferences')]); profile.value = hospital || {}; departments.value = normalizeDepartments(hospital?.departments); integrations.whatsapp = whatsapp || {}; integrations.sms = sms || {}; integrations.email = email || {}; templates.value = normalizeSettingsList<MessageTemplate>(templateList); notifications.value = normalizeSettingsList<Record<string, unknown>>(preferences) } catch (cause) { error.value = normalizeApiError(cause, 'Settings could not be loaded.') } finally { loading.value = false } }
  const saveHospital = async () => { saving.value = true; try { await $api.put('/hospital-profile', { ...profile.value, departments: departments.value }); await load() } finally { saving.value = false } }
  const saveIntegration = async (kind: 'whatsapp' | 'sms' | 'email') => { saving.value = true; try { const source = integrations[kind]; const payload = kind === 'whatsapp' ? { provider: source.provider || 'MetaCloud', phoneNumberId: source.phone_number_id || null, wabaId: source.waba_id || null, accessToken: shouldSendSecret(source.access_token) ? source.access_token : null, apiToken: shouldSendSecret(source.api_token) ? source.api_token : null, whatsBizBaseUrl: source.whats_biz_base_url || null, verifyToken: source.verify_token || null, appSecret: shouldSendSecret(source.app_secret) ? source.app_secret : null, businessName: source.business_name || null, enabled: Boolean(source.enabled) } : kind === 'sms' ? { gatewayUrl: source.gateway_url || null, apiKey: shouldSendSecret(source.api_key) ? source.api_key : null, senderId: source.sender_id || null, enabled: Boolean(source.enabled) } : { smtpHost: source.smtp_host || null, smtpPort: Number(source.smtp_port || 587), smtpUsername: source.smtp_username || null, smtpPassword: shouldSendSecret(source.smtp_password) ? source.smtp_password : null, useSsl: source.use_ssl !== false, fromEmail: source.from_email || null, fromName: source.from_name || null, enabled: Boolean(source.enabled), sendWithWhatsApp: source.send_with_whatsapp !== false }; await $api.post(`/settings/${kind}`, payload); await load() } finally { saving.value = false } }
  const saveNotifications = async () => { saving.value = true; try { await $api.put('/notification-preferences', { preferences: notifications.value }); await load() } finally { saving.value = false } }
  const createTemplate = async (payload: Record<string, unknown>) => { saving.value = true; try { await $api.post('/templates', payload); await load() } finally { saving.value = false } }
  const removeTemplate = async (id: string | number) => { await $api.delete(`/templates/${encodeURIComponent(String(id))}`); templates.value = templates.value.filter(item => item.id !== id) }
  return { profile, departments, integrations, templates, notifications, loading, saving, error, load, saveHospital, saveIntegration, saveNotifications, createTemplate, removeTemplate }
}
