<script setup lang="ts">
import { PhX } from '@phosphor-icons/vue'
import { employmentTypes, staffRoles } from '~/utils/staff'
import type { StaffDraft } from '~/composables/staff/useStaff'
const props = defineProps<{ open: boolean; draft: StaffDraft; departments: string[]; users: Array<{ id: string | number; name?: string; role?: string }>; saving: boolean; error?: string }>()
const emit = defineEmits<{ close: []; save: [] }>()
const eligibleUsers = computed(() => props.users.filter(user => ['doctor', 'nurse', 'staff', 'reception'].includes(String(user.role))))
</script>
<template>
  <div v-if="props.open" class="staff-modal" role="dialog" aria-modal="true"><button type="button" class="staff-modal-backdrop" aria-label="Close" @click="emit('close')" /><section class="staff-modal-panel"><header><div><p class="staff-eyebrow">Hospital staff</p><h2>New staff profile</h2></div><button type="button" class="staff-close" aria-label="Close" @click="emit('close')"><PhX :size="19" /></button></header><form @submit.prevent="emit('save')"><label>User account *<select v-model="props.draft.user_id" required><option value="">Select user</option><option v-for="user in eligibleUsers" :key="user.id" :value="user.id">{{ user.name || user.id }} ({{ staffRoles[user.role || ''] || user.role }})</option></select></label><div class="staff-form-grid"><label>Department<select v-model="props.draft.department"><option value="">Not specified</option><option v-for="department in props.departments" :key="department" :value="department">{{ department }}</option></select></label><label>Specialization<input v-model="props.draft.specialization" /></label><label>Qualification<input v-model="props.draft.qualification" /></label><label>Consultation fee (₹)<input v-model="props.draft.consultation_fee" type="number" min="0" /></label><label>Employment type<select v-model="props.draft.employment_type"><option v-for="(label, value) in employmentTypes" :key="value" :value="value">{{ label }}</option></select></label><label>Shift<input v-model="props.draft.shift" placeholder="Morning / Evening" /></label><label class="staff-form-full">Ward assignment<input v-model="props.draft.ward_assignment" /></label></div><p v-if="props.error" class="staff-form-error">{{ props.error }}</p><footer><button type="button" class="staff-secondary-button" @click="emit('close')">Cancel</button><button type="submit" class="staff-primary-button" :disabled="props.saving">{{ props.saving ? 'Creating…' : 'Create profile' }}</button></footer></form></section></div>
</template>
